---
- hosts: all
  user: vagrant
  sudo: true
  sudo_user: root

  vars:
    mongodb_user_admin_name: userAdmin
    mongodb_user_admin_password: admin
    mongodb_root_admin_name: rootAdmin
    mongodb_root_admin_password: admin
    nodejs_version: 5.10
    mongodb_security_authorization: enabled
    mongodb_users:
      - name: test
        password: developer
        roles: [readWrite, dbAdmin]
        database: testdb

  roles:
    - ansible_nodejs_5x
    - greendayonfire.mongodb
    # - role: ansible-nginx
    # - role: ansible-softwares
    # - role: ansible-mongodb
    # - role: DavidWittman.redis
    # - role: ansible-nodejs
    # - role: ansible-nodejs-apps
      # apps:
      #   enabled:
      #     - "/srv/myapp/"
      #     - "/srv/anotherapp/"
